### ISSUE TITLE
Tokenizer issue

### ISSUE THREAD

**Issue by authwork** [CyberZHG/keras-xlnet#11]
**Describe the Bug**

Unlike Tokenizer in keras-bert, the Tokenizer in keras-xlnet cannot load custom dict.

**Version Info**

* [x] I'm using the latest version

**Minimal Codes To Reproduce**

```python
import keras_xlnet

word_dict = load_dict()
tokenizer = Tokenizer(word_dict) # this works in keras_bert

pass
```

**Comment by CyberZHG** [comment]
Because XLNet uses sentence-piece module for tokenization. It's undefined if you just passing a word dictionary to the tokenizer.
