### ISSUE TITLE
对tensorflow2.0的兼容问题

### ISSUE THREAD

**Issue by liuzqiao** [CyberZHG/keras-xlnet#18]
我在使用
load_trained_model_from_checkpoint(config_path=config_files,
                                                     checkpoint_path=check_point_files,
                                                     target_len=max_length,
                                                     batch_size=8,
                                                     memory_len=0,
                                                     in_train_phase=False,
                                                     attention_type=ATTENTION_TYPE_BI)
这段代码记载模型时报这个错误：
AttributeError: module 'tensorflow' has no attribute 'placeholder'
请问这是因为我使用tensorflow2.0导致的问题吗？该如何解决呢

**Comment by CyberZHG** [comment]
Fixed.

**Comment by liuzqiao** [comment]
> Fixed.

感谢解答，我尝试了您的新代码，但在加载模型的时候仍然报错了，您能看看这个错误是什么原因吗？
错误信息如下：
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: Embed-Token_1/embeddings:0
仍然是模型加载的那段代码报的错，错误地方指向了下面的代码
keras_xlnet/loader.py in load_trained_model_from_checkpoint(config_path, checkpoint_path, batch_size, memory_len, target_len, in_train_phase, **kwargs)
    166         config=config,
    167         checkpoint_path=checkpoint_path,
--> 168         in_train_phase=in_train_phase,
    169     )
    170     return model
==================================
     70     model.get_layer(name='Embed-Token').set_weights([
---> 71         loader('model/transformer/word_embedding/lookup_table'),
     72     ])
