### ISSUE TITLE
tokenization 

### ISSUE THREAD

**Issue by xinsu626** [CyberZHG/keras-xlnet#3]
I went though your code, but didn't see the tokenizer class. Is there any tokenizer to use?

**Comment by CyberZHG** [comment]
Added.

```python
from keras_xlnet import Tokenizer
```

**Comment by xinsu626** [comment]
@CyberZHG 
Thanks a lot. I saw there were no truncate_pair, padding, segment etc. in your tokenization code. Do you have plan to add these into tokenization or this is the part that users should complete?

**Comment by xinsu626** [comment]
Close this issue. Since I was able to implement the tokenizer.
