### ISSUE TITLE
Supporrt Tensorflow 2 

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [CyberZHG/keras-xlnet#5]
Could you please kindly add TensorFlow 2 (call tf.keras, tf.data, tf.function, etc from TensorFlow 2) support for all NLP packages you have created.

I mean it would be great if your package support TensorFlow 2 grammar (such as tf.function, tf.data, etc)

**Comment by CyberZHG** [comment]
The repo has been tested under `tensorflow-2.0-beta1`. Add `TF_KERAS=1` to environment variables to switch the backend to `tf.keras`.

**Comment by ErmiaAzarkhalili** [comment]
Thanks for the reply.
Will it work for all other packages such as keras-bert, keras-gpt, etc?
Is it the permanent solution or just a temprorary solution?

**Comment by CyberZHG** [comment]
![image](https://user-images.githubusercontent.com/853842/61613927-1beafb80-ac95-11e9-80fc-3817eacde94e.png)

The badges show the supported backend. All the packages use the same mechanism.

**Comment by ErmiaAzarkhalili** [comment]
> ![image](https://user-images.githubusercontent.com/853842/61613927-1beafb80-ac95-11e9-80fc-3817eacde94e.png)
> 
> The badges show the supported backend. All the packages use the same mechanism.

I still receive the following error:   

'
     x = tf.placeholder(dtype, shape=shape, name=name)
    AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by CyberZHG** [comment]
Set the environment variable before importing the library.

```bash
export TF_KERAS=1
python xxx.py
```

or

```bash
TF_KERAS=1 python xxx.py
```

or

```python
import os
os.environ.setdefault("TF_KERAS", "1")
from keras_xlnet import *
```
