### ISSUE TITLE
Memory length in model initialization and Fine-tuning

### ISSUE THREAD

**Issue by xinsu626** [CyberZHG/keras-xlnet#8]
Hi, I was trying to use your keras_xlnet to fine tune on glue dataset, but didn't get results similar to the original tensorflow implementation and huggingface's implementation. I am thinking the memory length I used in model initialization and fine-tuning(mem_len in inputs) may be the issue. 

Do you have any  recommendations for these two parameters(should we use just length of 384)? Thank you.

**Comment by CyberZHG** [comment]
https://github.com/CyberZHG/keras-xlnet/tree/master/demo

**Comment by xinsu626** [comment]
Thanks.
